### ISSUE TITLE
Add a poison ivy, oak, sumac, vs safe plants model

### ISSUE THREAD

**Issue by robertleeplummerjr** [infinitered/keras-model-zoo#7]
How about rather than classify animals or cars, aka easy things for humans to identify, why not make a useful thing for humans.

After this issue is solved, if it is:
1. make an app with it that can run on smartphones
2. go explore the outdoors more safely with our families

**Comment by kevinvangelder** [comment]
@robertleeplummerjr Great idea, however this repo is for making it easy to download existing models for people to use in their projects and/or to learn how to use tools relating to machine learning, not for coming up with ideas with new models.

**Comment by robertleeplummerjr** [comment]
ah ok
